// <auto-generated />
using HallCrawler.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HallCrawler.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250531164250_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HallCrawler.Models.HallItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Services")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HallItems");
                });

            modelBuilder.Entity("HallCrawler.Models.MainWebCrawler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CssCellphoneHallSelector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssHallLinkSelector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssHallsSelector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssImageHallSelector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssInformationSelector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssManagerNameSelector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssPagnationLinkSelector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssPagnationSelector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssServicesSelector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssTelHallSelector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssTitleSelecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainWebCrawlers");
                });
#pragma warning restore 612, 618
        }
    }
}
